Resources:
  zeebeLambdaWorkerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: zeebe-lambda-worker-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement: # we are granting permission to ECS
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: zeebeWorkerInvokePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement: # we are granting the following permissions to the following resources
            - Effect: Allow
              Action:
              - lambda:InvokeFunction
              - lambda:InvokeAsync
            # resolves to 'arn:aws:lambda:*:<your-acct-id>:function:trip-booking-functions*'
              Resource: 
              - { 'Fn::Join': ['', ['arn:aws:lambda:', '*:',{ Ref: 'AWS::AccountId' }, ':function:', '${self:service}*']] }

